ungrouped:
  hosts:
    #   localhost:
    #     ansible_connection: local
    #     ansible_python_interpreter: /usr/bin/python
    rfnash-inspiron-alpine:
      ansible_host: 172.18.126.220
      ansible_port: 2222
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python
    raspberrypi:
      ansible_user: root
      ansible_python_interpreter: /usr/bin/python
