- hosts: all
  gather_facts: yes
  roles:
    - common
    - dotfiles
    - terminal-utilities
- hosts: rfnash-inspiron-alpine
  roles:
    - user
    - wsl
    - ansible
    - podman
- hosts: raspberrypi
  roles:
    - raspberrypi
  tasks:
    - name: Add group 'rfnash'
      ansible.builtin.group:
        name: rfnash
        state: present
        gid: 1000
    - name: Add user 'rfnash'
      ansible.builtin.user:
        name: rfnash
        state: present
        uid: 1000
        group: rfnash
        shell: /bin/zsh #TODO: might not work
    - name: Add 'rfnash' to sudoers
      community.general.sudoers:
        name: rfnash
        user: rfnash
        commands: ALL
        nopassword: true
        state: present
