- name: Install base packages
  community.general.apk:
    name:
      - alpine-baselayout
      - alpine-keys
      - apk-tools
      - bash
      - busybox
      - libc-utils
    state: present
- name: Create /etc/wsl.conf
  ansible.builtin.copy:
    content: |
      [boot]
      command = "/usr/bin/env -i /usr/bin/unshare --pid --mount-proc --fork --propagation private -- sh -c 'exec /sbin/init'"

      [network]
      hostname = {{ inventory_hostname }}

      [user]
      default = rfnash
    dest: /etc/wsl.conf
