- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
- name: Use 'edge' repositories
  ansible.builtin.copy:
    content: |
      https://dl-cdn.alpinelinux.org/alpine/edge/main
      https://dl-cdn.alpinelinux.org/alpine/edge/community
    dest: /etc/apk/repositories
- name: Perform system upgrade
  community.general.apk:
    update_cache: yes
    upgrade: yes
- name: Tailscale
  community.general.apk:
    name:
      - tailscale
    state: present

