- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
- name: Perform system upgrade
  community.general.apk:
    update_cache: yes
    upgrade: yes
- name: Install base packages
  community.general.apk:
    name:
      - alpine-baselayout
      - alpine-keys
      - apk-tools
      - bash
      - busybox
      - libc-utils
    state: present
- name: Tailscale
  community.general.apk:
    name:
      - tailscale
    state: present

